// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RealtorCAify.Data;

namespace RealtorCAify.Migrations
{
    [DbContext(typeof(RealtorCAifyDbContext))]
    partial class RealtorCAifyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("RealtorCAify.Models.ApiTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Request")
                        .HasColumnType("TEXT");

                    b.Property<string>("Resource")
                        .HasColumnType("TEXT");

                    b.Property<string>("Response")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ApiTransactions");
                });

            modelBuilder.Entity("RealtorCAify.Models.Listing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccessType")
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressText")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ammenities")
                        .HasColumnType("TEXT");

                    b.Property<string>("BathroomTotal")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bedrooms")
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailsUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("MlsNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("PropertyDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("RealtorName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultDtoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SizeFrontage")
                        .HasColumnType("TEXT");

                    b.Property<string>("SizeInterior")
                        .HasColumnType("TEXT");

                    b.Property<string>("SizeTotal")
                        .HasColumnType("TEXT");

                    b.Property<string>("StoriesTotal")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Listings");
                });
#pragma warning restore 612, 618
        }
    }
}
